Repository boostcampwm2023/iOS03-TravelShare, pull requests merged in 2023-12, with the labels that each got.

#163 [enhancement][#83] 글 작성 에러 수정
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadProfileView.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
Labels: enhancement🩹

#164 [chore] 키보드 숨기는 부분 util로 빼고, mypage에서도 사용할 수 있도록 구현
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyInfoViewController.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
  iOS/Macro/Macro/Util/UIViewController+.swift
Labels: enhancement🩹

#169 [chore][#168] 코드컨벤션 준수
  iOS/Macro/.swiftlint.yml
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Common/TabBar/View/TabBarViewController.swift
  iOS/Macro/Macro/Common/TabBar/ViewModel/TabBarViewModel.swift
  iOS/Macro/Macro/Common/UI/MacroCarouselView.swift
  iOS/Macro/Macro/Common/UI/MacroCarouselViewAddImageCell.swift
  iOS/Macro/Macro/Common/UI/MacroCarouselViewCell.swift
  iOS/Macro/Macro/Infrastructure/PersistentStorages/CacheManager.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeHeaderView.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/ViewModel/HomeViewModel.swift
  iOS/Macro/Macro/Scene/LocationInfo/InterfaceAdapters/VIew/LocationInfoViewController.swift
  iOS/Macro/Macro/Scene/Login/InterfaceAdapters/View/LoginViewController.swift
  iOS/Macro/Macro/Scene/Login/InterfaceAdapters/ViewModel/LoginViewModel.swift
  iOS/Macro/Macro/Scene/Login/Network/Model/LoginEndPoint.swift
  iOS/Macro/Macro/Scene/Login/Network/Model/RefreshTokenEndPoint.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/IntroductionEditView.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyInfoViewController.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageHeaderView.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/NameEditView.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/ViewModel/MyPageViewModel.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadProfileView.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/ViewModel/ReadViewModel.swift
  iOS/Macro/Macro/Scene/Read/Network/ReadEndPoint.swift
  iOS/Macro/Macro/Scene/Route/InterfaceAdapters/View/RouteViewController.swift
  iOS/Macro/Macro/Scene/Route/InterfaceAdapters/ViewModel/RouteViewModel.swift
  iOS/Macro/Macro/Scene/Search/InterfaceAdapters/View/SearchViewController.swift
  iOS/Macro/Macro/Scene/Search/InterfaceAdapters/ViewModel/SearchViewModel.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/RouteTableViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/SearchResultViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
  iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoHeaderView.swift
  iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoProfileView.swift
  iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoViewController.swift
  iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/ViewModel/UserInfoViewModel.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/ViewModel/WriteViewModel.swift
  iOS/Macro/Macro/Scene/Write/Network/ImageUploadEndPoint.swift
  iOS/Macro/Macro/Scene/Write/Network/PostUploadEndPoint.swift
  iOS/Macro/Macro/Util/CoreData/CoreDataManager.swift
  iOS/Macro/Macro/Util/CoreData/CoreDataStack.swift
  iOS/Macro/Macro/Util/Log.swift
Labels: enhancement🩹

#179 [feat][#178] Clova Sentiment API
  server/src/app.module.ts
  server/src/sentiment/sentiment.analysis.body.dto.ts
  server/src/sentiment/sentiment.analysis.response.dto.ts
  server/src/sentiment/sentiment.controller.ts
  server/src/sentiment/sentiment.module.ts
  server/src/sentiment/sentiment.service.ts
Labels: feature🔨

#181 [improve] [#180] ConfigModule 리팩토링과 타입 안정성 확보
  server/src/app.module.ts
  server/src/config/app.config.module.ts
  server/src/config/config.manager.module.ts
  server/src/config/config.manager.options.factory.ts
  server/src/config/config.manager.register.options.ts
  server/src/logger/logger.module.ts
  server/src/logger/ncp.elsa.logger.config.factory.ts
  server/src/sentiment/sentiment.analysis.config.dto.ts
  server/src/sentiment/sentiment.analysis.query.dto.ts
  server/src/sentiment/sentiment.analysis.request.dto.ts
  server/src/sentiment/sentiment.controller.ts
  server/src/sentiment/sentiment.module.ts
  server/src/sentiment/sentiment.service.ts
  server/src/user/user.followees.query.dto.ts
  server/src/user/user.followees.response.dto.ts
  server/src/user/user.followers.query.dto.ts
  server/src/user/user.followers.response.dto.ts
Labels: enhancement🩹

#184 [enhancement][#183] ReadView, WriteView UI 및 로직 관련 수정
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Common/CommonProtocol/CarouselViewProtocol.swift
  iOS/Macro/Macro/Common/Entities/CarouselEntities/CarouselViewType.swift
  iOS/Macro/Macro/Common/Entities/Post.swift
  iOS/Macro/Macro/Common/UI/CarouselView/MacroCarouselCollectionView.swift
  iOS/Macro/Macro/Common/UI/CarouselView/MacroCarouselView.swift
  iOS/Macro/Macro/Common/UI/CarouselView/MacroCarouselViewAddImageCell.swift
  iOS/Macro/Macro/Common/UI/CarouselView/MacroCarouselViewCell.swift
  iOS/Macro/Macro/Common/UI/CarouselView/MacroCarouselViewCelladdPictureComponentView.swift
  iOS/Macro/Macro/Common/UI/CarouselView/MacroCarouselViewCelladdPictureView.swift
  iOS/Macro/Macro/Common/UI/MacroCarouselView.swift
  iOS/Macro/Macro/Common/UI/MacroCarouselViewAddImageCell.swift
  iOS/Macro/Macro/Common/UI/MacroCarouselViewCell.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadProfileView.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/ViewModel/ReadViewModel.swift
  iOS/Macro/Macro/Scene/Route/InterfaceAdapters/View/RouteViewController.swift
  iOS/Macro/Macro/Scene/Route/InterfaceAdapters/ViewModel/RouteViewModel.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/ViewModel/WriteViewModel.swift
  iOS/MacroDesignSystem/Sources/MacroDesignSystem/UIColor+.swift
Labels: enhancement🩹

#190 [feat][#189] coredata Entity 추가 및 Relationship설정
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Common/UI/CarouselView/MacroCarouselView.swift
  iOS/Macro/Macro/Common/UI/MapCollectionView/MapCollectionViewCellContentView.swift
  iOS/Macro/Macro/Common/UI/MapCollectionView/MapCollectionViewCellHeaderView.swift
  iOS/Macro/Macro/CoreData/Macro.xcdatamodeld/Model.xcdatamodel/contents
  iOS/Macro/Macro/CoreData/RecordedPinnedLocationMO+CoreDataClass.swift
  iOS/Macro/Macro/CoreData/TravelMO+CoreDataClass.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
  iOS/Macro/Macro/Scene/Travel/Entities/PinnedLocation.swift
  iOS/Macro/Macro/Scene/Travel/Entities/RecordedPinnedLocation.swift
  iOS/Macro/Macro/Scene/Travel/Entities/TravelInfo.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
  iOS/Macro/Macro/Util/CoreData/CoreDataManager.swift
  iOS/Macro/RecordedPinnedLocationMO+CoreDataClass.swift
  iOS/Macro/RecordedPinnedLocationMO+CoreDataProperties.swift
  iOS/Macro/TravelMO+CoreDataClass.swift
  iOS/Macro/TravelMO+CoreDataProperties.swift
Labels: feature🔨

#191 [feat][#188] 프로필 이미지 수정, 유저 이름으로 검색
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Common/Entities/UserProfile.swift
  iOS/Macro/Macro/Common/TabBar/ViewModel/TabBarViewModel.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionViewCell.swift
  iOS/Macro/Macro/Common/UseCases/SearchUseCase.swift
  iOS/Macro/Macro/Infrastructure/PersistentStorages/ImageSaveManager.swift
  iOS/Macro/Macro/Scene/LocationInfo/Entities/InfoType.swift
  iOS/Macro/Macro/Scene/LocationInfo/Entities/RelatedLocation.swift
  iOS/Macro/Macro/Scene/LocationInfo/Network/LocationInfoEndPoint.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/ViewModel/MyPageViewModel.swift
  iOS/Macro/Macro/Scene/MyPage/Network/UpdateUserEndPoint.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
  iOS/Macro/Macro/Scene/Search/InterfaceAdapters/View/SearchViewController.swift
  iOS/Macro/Macro/Scene/Search/InterfaceAdapters/View/UserResultCell.swift
  iOS/Macro/Macro/Scene/Search/InterfaceAdapters/View/UserResultCollectionView.swift
  iOS/Macro/Macro/Scene/Search/InterfaceAdapters/ViewModel/SearchViewModel.swift
  iOS/Macro/Macro/Scene/Search/Network/PostFindEndPoint.swift
  iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/ViewModel/UserInfoViewModel.swift
Labels: feature🔨

#193 [feat][#192] View Issue 해결 및 불필요한 Print문 제거
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
  iOS/Macro/Macro/Scene/Travel/UseCases/RouteRecorder.swift
Labels: feature🔨

#195 [feat][#194] 위, 경도 이슈 해결
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
Labels: feature🔨

#197 [feat][#196] post refresh, post load 구현
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionView.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionViewModel.swift
  iOS/Macro/Macro/Common/UseCases/SearchUseCase.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/ViewModel/HomeViewModel.swift
  iOS/Macro/Macro/Scene/Home/Network/PostEndPoint.swift
Labels: feature🔨

#202 [feat & improve & add] [#198, #199, #200, #201] Redis 연동, 검색, 캐싱, 인기도 모델 등
  server/.gitignore
  server/README.md
  server/docker-compose.yaml
  server/package-lock.json
  server/package.json
  server/src/config/config.manager.module.ts
  server/src/config/config.manager.register.options.ts
  server/src/entities/post.entity.ts
  server/src/post/post.config.dto.ts
  server/src/post/post.controller.ts
  server/src/post/post.module.ts
  server/src/post/post.service.ts
  server/src/sentiment/sentiment.controller.ts
  server/src/sentiment/sentiment.service.ts
  server/src/user/user.profile.simple.response.dto.ts
  server/src/utils/keyword.autocomplete.service.ts
  server/src/utils/redis/redis.client.config.dto.ts
  server/src/utils/redis/redis.client.config.socket.dto.ts
  server/src/utils/redis/redis.client.factory.ts
  server/src/utils/redis/redis.client.provide.token.ts
  server/src/utils/redis/redis.client.type.ts
  server/src/utils/redis/redis.module.ts
  server/src/utils/redis/redis.service.ts
  server/src/utils/utils.module.ts
  server/static/image.png
Labels: enhancement🩹, feature🔨, add

#204 [fix][#165] Image 없으면 글 작성 안되는 문제 해결
  iOS/Macro/Macro/Infrastructure/PersistentStorages/ImageSaveManager.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/ViewModel/WriteViewModel.swift
Labels: bug fix🐛

#206 [feat][#205] 라이프 사이클에 애니메이션 시작, 종료 함수 추가
  iOS/Macro/Macro/Common/TabBar/View/TaBarBackgroundLineView.swift
  iOS/Macro/Macro/Common/TabBar/View/TabBarViewController.swift
Labels: enhancement🩹

#211 [feat][#210] 수출 규정 관련 문서 관련 Plist 수정
  iOS/Macro/Macro/Info.plist
Labels: feature🔨

#214 [enhancement]
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/ViewModel/WriteViewModel.swift
Labels: enhancement🩹

#219 [fix][#215] ReadView Map 비정상 표기 수정
  iOS/Macro/Macro/Scene/Read/Entities/ReadPost.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
Labels: bug fix🐛

#221 [enhancement][#220] ReadView UI Figma에 맞게 수정
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostContentView.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/ViewModel/ReadViewModel.swift
Labels: enhancement🩹

#225 [fix] [#224] post 오류 수정
  server/src/post/post.find.response.dto.ts
  server/src/post/post.service.ts
Labels: bug fix🐛

#226 [feat][#218] travel View 디테일
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Common/TabBar/View/TaBarBackgroundLineView.swift
  iOS/Macro/Macro/Common/TabBar/View/TabBarBackgroundLargeCirclceView.swift
  iOS/Macro/Macro/Common/TabBar/View/TabBarCenterView.swift
  iOS/Macro/Macro/Common/TabBar/View/TabComponentView.swift
  iOS/Macro/Macro/Common/TabBar/ViewModel/TabBarViewModel.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionViewModel.swift
  iOS/Macro/Macro/Scene/Travel/Entities/ModalViewSize.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/RouteModalViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/RouteTableViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift
  iOS/Macro/Macro/Util/CAGradientLayer+.swift
  iOS/MacroDesignSystem/Sources/MacroDesignSystem/UIColor+.swift
Labels: enhancement🩹

#228 [feat][#227] 문의하기 기능구현
  iOS/Macro/Macro/Info.plist
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/ViewModel/MyPageViewModel.swift
Labels: feature🔨

#231 [fix][#230] Image Upload 및 Read 순차적으로 될 수 있도록 수정
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/ViewModel/WriteViewModel.swift
Labels: bug fix🐛

#232 [fix][#213] 컬렉션뷰 문제해결
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionViewCell.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostContentView.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostProfileView.swift
  iOS/Macro/Macro/Scene/LocationInfo/InterfaceAdapters/ViewModel/LocationInfoViewModel.swift
Labels: bug fix🐛

#235 [improve] [#234] Post Hits, Search 캐싱
  server/package-lock.json
  server/package.json
  server/src/auth/apple/apple.auth.service.ts
  server/src/post/post.service.ts
  server/src/utils/logger.interceptor.ts
  server/src/utils/utils.module.ts
Labels: enhancement🩹

#233 [feat][#229] 회원 탈퇴 구현
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/App/SceneDelegate.swift
  iOS/Macro/Macro/Common/Entities/CustomAlert/AddAction.swift
  iOS/Macro/Macro/Common/TabBar/ViewModel/TabBarViewModel.swift
  iOS/Macro/Macro/Common/UI/AlertView/CustomAlertViewController.swift
  iOS/Macro/Macro/Scene/Login/InterfaceAdapters/View/LoginViewController.swift
  iOS/Macro/Macro/Scene/MyPage/Entities/AppleRevokeResponse.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController+AuthenticationServices.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/ViewModel/MyPageViewModel.swift
  iOS/Macro/Macro/Scene/MyPage/Network/RevokeEndPoint.swift
  iOS/Macro/Macro/Scene/MyPage/UseCases/RevokeUseCase.swift
  iOS/Macro/Macro/Util/AlertBuilder.swift
Labels: feature🔨

#238 [enhancement] 여행 상세보기 layout 디테일, carousel collectionView 디테일
  iOS/Macro/Macro/Common/UI/CarouselView/MacroCarouselCollectionView.swift
  iOS/Macro/Macro/Common/UI/MapCollectionView/MapCollectionViewCellContentView.swift
  iOS/Macro/Macro/Scene/LocationInfo/InterfaceAdapters/VIew/LocationInfoViewController.swift
Labels: enhancement🩹

#240 [enhancement][#239] 각종 이슈 처리
  iOS/Macro/Macro/Common/UI/AlertView/CustomAlertViewController.swift
  iOS/Macro/Macro/Common/UI/MapCollectionView/MapCollectionViewCellContentView.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionView.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
  iOS/Macro/Macro/Scene/Search/InterfaceAdapters/View/SearchViewController.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
Labels: enhancement🩹

#241 [fix][#233] 회원탈퇴 로직 수정
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController+AuthenticationServices.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/ViewModel/MyPageViewModel.swift
  iOS/Macro/Macro/Scene/MyPage/Network/RevokeEndPoint.swift
  iOS/Macro/Macro/Scene/MyPage/UseCases/RevokeUseCase.swift
Labels: bug fix🐛

#256 [enhancement][#255] Refresh 실패 시 로그인 화면으로 넘어가도록 설정
  iOS/Macro/Macro/App/SceneDelegate.swift
  iOS/Macro/Macro/Infrastructure/PersistentStorages/TokenManager.swift
Labels: enhancement🩹

#260 [fix][#258] readView 수정
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
Labels: bug fix🐛

#263 [fix][#244] travel page 버그 fix
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadProfileView.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/ViewModel/ReadViewModel.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
  iOS/Macro/Macro/Scene/Travel/Service/LocationManager.swift
Labels: bug fix🐛

#265 [feat][#264] collectionView diffabledatasource 적용
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Common/Entities/PostFindResponse+Hashable.swift
  iOS/Macro/Macro/Common/UI/CarouselView/MacroCarouselCollectionView.swift
  iOS/Macro/Macro/Common/UI/CarouselView/MacroCarouselViewCell.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionView.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionViewCell.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionViewModel.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostContentView.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostProfileView.swift
  iOS/Macro/Macro/Resource/Assets.xcassets/DisConnectWifi.imageset/Contents.json
  iOS/Macro/Macro/Resource/Assets.xcassets/DisConnectWifi.imageset/DisConnectWifi.svg
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
  iOS/Macro/Macro/Scene/LocationInfo/InterfaceAdapters/VIew/LocationInfoViewController.swift
  iOS/Macro/Macro/Scene/LocationInfo/InterfaceAdapters/ViewModel/LocationInfoViewModel.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadProfileView.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/ViewModel/ReadViewModel.swift
  iOS/Macro/Macro/Scene/Search/InterfaceAdapters/View/SearchViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/SearchResultViewController.swift
  iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoViewController.swift
  iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/ViewModel/UserInfoViewModel.swift
  iOS/MacroDesignSystem/Sources/MacroDesignSystem/UIImage+.swift
Labels: feature🔨

#269 [improve] [#268] post refactoring
  server/src/post/post.cache.repository.ts
  server/src/post/post.controller.ts
  server/src/post/post.module.ts
  server/src/post/post.service.ts
  server/src/user/user.profile.simple.response.dto.ts
  server/src/utils/keyword.autocomplete.service.ts
  server/src/utils/redis/redis.module.ts
  server/src/utils/redis/redis.service.ts
Labels: enhancement🩹

#273 [fix][#244] travel page 버그 다수 수정 및 개선
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/App/AppDelegate.swift
  iOS/Macro/Macro/Common/TabBar/ViewModel/TabBarViewModel.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/FollowResultCell.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/RouteModalViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/SearchResultViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
  iOS/Macro/Macro/Scene/Travel/Service/LocationManager.swift
  iOS/Macro/Macro/Scene/Travel/UseCases/RouteRecorder.swift
  iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoHeaderView.swift
  iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoViewController.swift
  iOS/MacroDesignSystem/Sources/MacroDesignSystem/UIImage+.swift
Labels: feature🔨, bug fix🐛

#274 [feat][#266] 게시글 신고기능 추가
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro.xcodeproj/xcshareddata/xcschemes/Macro.xcscheme
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostContentView.swift
  iOS/Macro/Macro/Scene/Read/Entities/ReportResponse.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/ViewModel/ReadViewModel.swift
  iOS/Macro/Macro/Scene/Read/Network/ReportEndPoint.swift
  iOS/Macro/Macro/Scene/Read/UseCases/ReportUseCase.swift
  iOS/MacroDesignSystem/Sources/MacroDesignSystem/UIImage+.swift
Labels: feature🔨

#275 [feat][#272] 여행 경로가 없을 때, 여행페이지로 이동하는 UI, 로직, profile Image radius 오류 수정
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Common/TabBar/Model/TabComponent.swift
  iOS/Macro/Macro/Common/TabBar/Model/TabbarType.swift
  iOS/Macro/Macro/Common/TabBar/View/TabBarCenterView.swift
  iOS/Macro/Macro/Common/TabBar/View/TabBarViewController.swift
  iOS/Macro/Macro/Common/TabBar/ViewModel/TabBarViewModel.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostProfileView.swift
  iOS/Macro/Macro/Scene/Route/InterfaceAdapters/View/RouteViewController.swift
  iOS/Macro/Macro/Scene/Route/InterfaceAdapters/ViewModel/RouteViewModel.swift
  iOS/Macro/Macro/Scene/Search/InterfaceAdapters/View/SearchViewController.swift
  iOS/Macro/Macro/Scene/Search/InterfaceAdapters/ViewModel/SearchViewModel.swift
Labels: feature🔨

#280 [fix][#244] travelpage 버그 추가 수정 및 기능 추가
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadProfileView.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/ViewModel/ReadViewModel.swift
  iOS/Macro/Macro/Scene/Search/InterfaceAdapters/View/SearchViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/RouteModalViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
  iOS/Macro/Macro/Scene/Travel/Service/LocationManager.swift
  iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoHeaderView.swift
Labels: feature🔨, bug fix🐛

#281 [feat][ #279] DataEmptyView 작업
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Common/UI/CarouselView/MacroCarouselCollectionView.swift
  iOS/Macro/Macro/Common/UI/EmptyView/DataEmptyView.swift
  iOS/Macro/Macro/Common/UI/MapCollectionView/MapCollectionViewCellContentView.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostContentView.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostProfileView.swift
  iOS/Macro/Macro/Resource/Assets.xcassets/EmptyImage.imageset/Contents.json
  iOS/Macro/Macro/Resource/Assets.xcassets/EmptyImage.imageset/EmptyImage.svg
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/FollowResultCell.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageHeaderView.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
  iOS/Macro/Macro/Scene/NetworkUnresearchable/NetworkUnresearchableViewController.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadProfileView.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/ViewModel/ReadViewModel.swift
  iOS/Macro/Macro/Scene/Route/InterfaceAdapters/View/RouteViewController.swift
  iOS/Macro/Macro/Scene/Search/InterfaceAdapters/View/UserResultCell.swift
  iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoProfileView.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
  iOS/MacroDesignSystem/Sources/MacroDesignSystem/UIImage+.swift
Labels: feature🔨

#284 [feat] travel page 폰트 수정, locationinfo 버그 수정
  iOS/Macro/Macro/Scene/LocationInfo/Entities/RelatedLocation.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/RouteModalViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/SearchResultViewController.swift
Labels: feature🔨, bug fix🐛

#283 [enhancement][#282] 각종 이슈해결
  iOS/Macro/Macro/Common/Entities/Writer.swift
  iOS/Macro/Macro/Common/UI/MapCollectionView/MapCollectionViewCellContentView.swift
  iOS/Macro/Macro/Scene/LocationInfo/InterfaceAdapters/VIew/LocationInfoViewController.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
Labels: enhancement🩹

#277 [fix] [#276] post multi get
  server/src/post/post.cache.repository.ts
  server/src/post/post.service.ts
Labels: bug fix🐛

#288 [fix] [#278, #287] user follower
  server/src/auth/apple/apple.auth.service.ts
  server/src/auth/apple/apple.module.ts
  server/src/auth/authentication.dto.ts
  server/src/entities/place.entity.ts
  server/src/entities/post.entity.ts
  server/src/entities/report.entity.ts
  server/src/entities/route.entity.ts
  server/src/entities/user.entity.ts
  server/src/migrations/1702220670805-Migration.ts
  server/src/user/user.service.ts
Labels: bug fix🐛

#286 [enhancement][#251] 상세 페이지의 변경 내용을 CollectionView에 반영
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionView.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionViewCell.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostContentView.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/ViewModel/ReadViewModel.swift
Labels: enhancement🩹

#292 [enhancement][#291] 위치, 사진 이용동의 문구 수정, 로그아웃 추가, 회원탈퇴 로직 수정
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/ViewModel/MyPageViewModel.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
Labels: enhancement🩹

#294 [feature] 이미지와 Pin 매핑
  iOS/Macro/Macro/Common/UI/MapCollectionView/MapCollectionViewCellContentView.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/ViewModel/WriteViewModel.swift
Labels: feature🔨, bug fix🐛

#300 [fix] [#298, #299] 게시글 개수 로딩, typeorm error
  server/src/post/post.cache.repository.ts
  server/src/utils/utils.module.ts
Labels: bug fix🐛

#302 [fix][#251] 조회수 반영 안되던 문제 해결
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionView.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionViewCell.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostContentView.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
  iOS/Macro/Macro/Scene/Read/Entities/ReadPost.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/ViewModel/ReadViewModel.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
Labels: bug fix🐛

#304 [chore][#303] 회원탈퇴 관련 로직 수정 및 불필요한 print 삭제
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/ViewModel/MyPageViewModel.swift
Labels: bug fix🐛

#307 [fix] server error
  server/docker-compose.yaml
  server/src/auth/apple/apple.auth.service.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/entities/place.entity.ts
  server/src/entities/report.entity.ts
  server/src/migrations/1701243623710-Migration.ts
  server/src/migrations/1701250342199-Migration.ts
  server/src/migrations/1701280194449-Migration.ts
  server/src/migrations/1701544638192-Migration.ts
  server/src/migrations/1701750909254-Migration.ts
  server/src/migrations/1701763230245-Migration.ts
  server/src/migrations/1701877593464-Migration.ts
  server/src/migrations/1702067556528-Migration.ts
  server/src/migrations/1702220670805-Migration.ts
  server/src/migrations/1702292664933-Migration.ts
  server/src/post/place.base.dto.ts
  server/src/post/post.cacheable.service.ts
  server/src/post/post.module.ts
  server/src/post/post.service.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
  server/src/user/user.subscriber.ts
  server/src/utils/utils.module.ts
Labels: bug fix🐛

#309 [fix] [#308] 회원 탈퇴 시 토큰 관리
  server/src/auth/apple/apple.auth.service.ts
  server/src/auth/auth.module.ts
  server/src/auth/blacklist/blacklist.module.ts
  server/src/auth/blacklist/user.blacklist.manager.ts
  server/src/auth/jwt.authentication.gaurd.ts
  server/src/user/user.subscriber.ts
  server/src/utils/redis/redis.service.ts
Labels: bug fix🐛

#312 [fix] 앱 초기 위치 권한에 따른 분기 처리
  iOS/Macro/Macro/Scene/LocationInfo/InterfaceAdapters/ViewModel/LocationInfoViewModel.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadProfileView.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
  iOS/Macro/Macro/Scene/Travel/Service/LocationManager.swift
Labels: bug fix🐛

#313 [chore][#310] MyInfo CustomAleart 변경
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyInfoViewController.swift
Labels: feature🔨

#315 [feat][#314] edit InfoPlist
  iOS/Macro/Macro.xcodeproj/project.pbxproj
Labels: feature🔨

#316 [chore] 버그리포팅 피드백 적용
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostContentView.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostProfileView.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift
Labels: enhancement🩹

#319 [fix][#316] 매핑안된 이미지가 스크롤 되면 기존에 매핑 지우기
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
Labels: bug fix🐛

#323 [fix][#322] Introduce Issue 해결
  iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoProfileView.swift
Labels: enhancement🩹

#324 [docs] ReadMe 업데이트
  README.md
Labels: document

#327 [feat][#326] 네이버지도 최소 zoomLevel 설정
  iOS/Macro/Macro/Common/UI/MapCollectionView/MapCollectionViewCellContentView.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
Labels: feature🔨

#325 [fix] main page에서만 조회수, 좋아요가 반영되던 버그 수정
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionView.swift
Labels: bug fix🐛

#330 [feat][#329] 유저 정보 동의 화면 구현
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/App/SceneDelegate.swift
  iOS/Macro/Macro/Infrastructure/PersistentStorages/TokenManager.swift
  iOS/Macro/Macro/Scene/Login/InterfaceAdapters/View/LoginViewController.swift
  iOS/Macro/Macro/Scene/UserAgreement/InterfaceAdapters/Entities/UserAgreementModel.swift
  iOS/Macro/Macro/Scene/UserAgreement/InterfaceAdapters/View/UserAgreementHeaderView.swift
  iOS/Macro/Macro/Scene/UserAgreement/InterfaceAdapters/View/UserAgreementTapView.swift
  iOS/Macro/Macro/Scene/UserAgreement/InterfaceAdapters/View/UserAgreementViewController.swift
  iOS/Macro/Macro/Scene/UserAgreement/InterfaceAdapters/ViewModel/UserAgreementViewModel.swift
  iOS/MacroDesignSystem/Sources/MacroDesignSystem/UIColor+.swift
  iOS/MacroDesignSystem/Sources/MacroDesignSystem/UIImage+.swift
Labels: feature🔨

#331 [fix] 코어데이터 컬렉션뷰 재사용 문제 해결, 경로 기록 관련 개선
  iOS/Macro/Macro/Common/UI/MapCollectionView/MapCollectionViewCellContentView.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
Labels: enhancement🩹, bug fix🐛

#335 [chore] 앱 시연 영상 수정
  README.md
Labels: enhancement🩹
