Repository boostcampwm2023/iOS03-TravelShare, pull requests merged in 2023-11, with the labels that each got.

#6 [add][#3] SwiftLint 적용 및 프로젝트 생성
  .github/ISSUE_TEMPLATE/작업-이슈-템플릿.md
  .github/pull_request_template.md
  .gitignore
  README.md
  iOS/Macro/.swiftlint.yml
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/Macro/Macro.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/Macro/Macro.xcworkspace/contents.xcworkspacedata
  iOS/Macro/Macro.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/Macro/Macro/AppDelegate.swift
  iOS/Macro/Macro/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/Macro/Macro/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/Macro/Macro/Assets.xcassets/Contents.json
  iOS/Macro/Macro/Base.lproj/LaunchScreen.storyboard
  iOS/Macro/Macro/Base.lproj/Main.storyboard
  iOS/Macro/Macro/Info.plist
  iOS/Macro/Macro/SceneDelegate.swift
  iOS/Macro/Macro/ViewController.swift
  iOS/Macro/Podfile
  iOS/Macro/Podfile.lock
Labels: feature🔨

#8 [file][#3] 프로젝트 세팅 수정
  .gitignore
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/AppDelegate.swift
  iOS/Macro/Macro/Base.lproj/LaunchScreen.storyboard
  iOS/Macro/Macro/Base.lproj/Main.storyboard
  iOS/Macro/Macro/Info.plist
  iOS/Macro/Macro/SceneDelegate.swift
  iOS/Macro/Podfile.lock
Labels: feature🔨

#9 [move][#3] 폴더 구조 변경
  iOS/Macro/.swiftlint.yml
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/App/AppDelegate.swift
  iOS/Macro/Macro/App/SceneDelegate.swift
  iOS/Macro/Macro/Info.plist
  iOS/Macro/Macro/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/Macro/Macro/Resource/Assets.xcassets/Contents.json
  iOS/Macro/Macro/Scene/Home/Model/.gitkeep
  iOS/Macro/Macro/Scene/Home/View/HomeViewController.swift
  iOS/Macro/Macro/Scene/Home/ViewModel/.gitkeep
  iOS/MacroDesignSystem/.gitignore
  iOS/MacroDesignSystem/Package.swift
  iOS/MacroDesignSystem/Sources/MacroDesignSystem/UIColor+.swift
  iOS/MacroDesignSystem/Sources/MacroDesignSystem/UIFont+.swift
  iOS/MacroDesignSystem/Tests/MacroDesignSystemTests/MacroDesignSystemTests.swift
Labels: feature🔨

#14 [feature] [#13] 지도 검색 api 사용, api 전달
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/config/app.config.module.ts
  server/src/config/app.config.ts
  server/src/entities/post.entity.ts
  server/src/entities/user.entity.ts
  server/src/map/map.controller.ts
  server/src/map/map.module.ts
  server/src/map/map.search.response.dto.ts
  server/src/map/map.service.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.profile.query.dto.ts
  server/src/user/user.profile.response.dto.ts
  server/src/user/user.profile.simple.response.dto.ts
  server/src/user/user.service.ts
  server/src/user/user.signin.body.dto.ts
  server/src/user/user.signup.body.dto.ts
Labels: feature🔨

#19 [feat][#11] Travel하는 페이지의 MVVM 설계 및 구현
  iOS/Macro/.swiftlint.yml
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Info.plist
  iOS/Macro/Macro/Scene/Travel/Entities/LocationDetail.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/RouteTableViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/RouteTableViewControllerDelegate.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/SearchResultViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
  iOS/Macro/Macro/Scene/Travel/Network/TravelEndPoint.swift
  iOS/Macro/Macro/Scene/Travel/UseCases/LocationSearcher.swift
  iOS/Macro/Macro/Scene/Travel/UseCases/PinnedPlaceManager.swift
  iOS/Macro/Macro/Scene/Travel/UseCases/RouteRecorder.swift
  iOS/Macro/Macro/Scene/ViewModelProtocol.swift
  iOS/Macro/Podfile
  iOS/MacroDesignSystem/Package.swift
  iOS/MacroDesignSystem/Sources/Network/APIProvider.swift
  iOS/MacroDesignSystem/Sources/Network/EndPoint.swift
  iOS/MacroDesignSystem/Sources/Network/HTTPHeader.swift
  iOS/MacroDesignSystem/Sources/Network/HTTPHeaders.swift
  iOS/MacroDesignSystem/Sources/Network/HTTPMethod.swift
  iOS/MacroDesignSystem/Sources/Network/HTTPParameter.swift
  iOS/MacroDesignSystem/Sources/Network/NetworkError.swift
  iOS/MacroDesignSystem/Sources/Network/Requestable.swift
  iOS/MacroDesignSystem/Sources/Network/Session.swift
  iOS/MacroDesignSystem/Tests/NetworkTests/NetworkTests.swift
Labels: feature🔨

#17 [add][#10] DesignSystem color, image Asset 추가
  iOS/MacroDesignSystem/Sources/MacroDesignSystem/UIColor+.swift
  iOS/MacroDesignSystem/Sources/MacroDesignSystem/UIImage+.swift
Labels: feature🔨

#22 [feat][#21] app Icon 추가
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/100.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/128.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/144.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/152.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/16.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/167.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/172.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/196.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/20.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/216.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/256.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/32.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/48.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/50.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/512.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/55.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/64.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/66.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/72.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/76.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/88.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/92.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/Macro/Macro/Resource/Assets.xcassets/LogoImage.imageset/Contents.json
  iOS/Macro/Macro/Resource/Assets.xcassets/LogoImage.imageset/LogoImage.svg
  iOS/MacroDesignSystem/Sources/MacroDesignSystem/UIImage+.swift
Labels: feature🔨

#20 [feat][#15] Custom tabbar 구현
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Common/TabBar/Model/TabComponent.swift
  iOS/Macro/Macro/Common/TabBar/Model/TabLocation.swift
  iOS/Macro/Macro/Common/TabBar/View/TabBarBackgroundLargeCirclceView.swift
  iOS/Macro/Macro/Common/TabBar/View/TabBarBackgroundSmallView.swift
  iOS/Macro/Macro/Common/TabBar/View/TabBarCenterView.swift
  iOS/Macro/Macro/Common/TabBar/View/TabBarOpacityView.swift
  iOS/Macro/Macro/Common/TabBar/View/TabBarViewController.swift
  iOS/Macro/Macro/Common/TabBar/View/TabComponentView.swift
  iOS/Macro/Macro/Common/TabBar/ViewModel/TabBarViewModel.swift
  iOS/Macro/Macro/Util/CAGradientLayer+.swift
  iOS/Macro/Macro/Util/CircularViewProtocol.swift
  iOS/Macro/Macro/Util/UIScreen+.swift
Labels: feature🔨

#26 [feat] [#12] Backend Apple Login 구현, JWT 토큰 발급 연동
  server/.gitignore
  server/src/app.module.ts
  server/src/auth/apple/apple.auth.controller.ts
  server/src/auth/apple/apple.auth.revoke.body.dto.ts
  server/src/auth/apple/apple.auth.service.ts
  server/src/auth/apple/apple.auth.token.body.dto.ts
  server/src/auth/apple/apple.auth.token.response.dto.ts
  server/src/auth/apple/apple.client.auth.body.dto.ts
  server/src/auth/apple/apple.client.auth.response.dto.ts
  server/src/auth/apple/apple.client.revoke.body.dto.ts
  server/src/auth/apple/apple.identity.token.header.dto.ts
  server/src/auth/apple/apple.identity.token.payload.dto.ts
  server/src/auth/apple/apple.identity.token.public.keys.response.dto.ts
  server/src/auth/apple/apple.module.ts
  server/src/auth/auth.constants.ts
  server/src/auth/auth.decorators.ts
  server/src/auth/auth.module.ts
  server/src/auth/authentication.dto.ts
  server/src/auth/jwt.authentication.gaurd.ts
  server/src/auth/role.authorization.gaurd.ts
  server/src/config/app.config.module.ts
  server/src/config/app.config.ts
  server/src/entities/apple.auth.entity.ts
  server/src/entities/post.entity.ts
  server/src/entities/user.entity.ts
  server/src/main.ts
  server/src/map/map.module.ts
  server/src/map/map.search.response.dto.ts
  server/src/map/map.service.ts
  server/src/post/post.controller.ts
  server/src/post/post.find.query.dto.ts
  server/src/post/post.find.response.dto.ts
  server/src/post/post.module.ts
  server/src/post/post.read.response.dto.ts
  server/src/post/post.service.ts
  server/src/post/post.write.body.ts
  server/src/user/user.controller.ts
  server/src/user/user.delete.body.dto.ts
  server/src/user/user.profile.simple.response.dto.ts
  server/src/user/user.service.ts
  server/src/user/user.signin.body.dto.ts
  server/src/user/user.signin.response.dto.ts
  server/src/user/user.signup.body.dto.ts
  server/src/utils/response.validation.interceptor.ts
  server/src/utils/transactional.decorator.ts
  server/src/utils/utils.module.ts
Labels: feature🔨

#37 [Improve] #25 naver api to kakao api
  server/.eslintrc.js
  server/src/map/map.kakao.controller.ts
  server/src/map/map.kakao.search.response.dto.ts
  server/src/map/map.kakao.service.ts
  server/src/map/map.module.ts
Labels: enhancement🩹

#38 [Add] merge Improve/kakaomap to Dev
  server/.eslintrc.js
  server/src/map/map.kakao.controller.ts
  server/src/map/map.kakao.search.response.dto.ts
  server/src/map/map.kakao.service.ts
  server/src/map/map.module.ts
Labels: add

#27 [feat][#11] travel page의 추가적인 기능 구현
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Scene/Travel/Entities/SavedRoute.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/RouteTableViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/SearchResultViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
  iOS/Macro/Macro/Scene/Travel/UseCases/LocationSearcher.swift
  iOS/Macro/Macro/Scene/Travel/UseCases/PinnedPlaceManager.swift
  iOS/Macro/Macro/Scene/Travel/UseCases/RouteRecorder.swift
  iOS/MacroDesignSystem/Sources/Network/APIProvider.swift
Labels: feature🔨

#31 [feat][#23] HomeView UI 및 로직 작업
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Common/TabBar/View/TaBarBackgroundLineView.swift
  iOS/Macro/Macro/Common/TabBar/View/TabBarViewController.swift
  iOS/Macro/Macro/Resource/MockJson.json
  iOS/Macro/Macro/Scene/Home/Entities/PostResponse.swift
  iOS/Macro/Macro/Scene/Home/Entities/RouteInfo.swift
  iOS/Macro/Macro/Scene/Home/Entities/UserInfo.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeCollectionView.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeHeaderView.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/PostCollectionViewCell.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/PostContentView.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/PostProfileView.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/ViewModel/.gitkeep
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/ViewModel/HomeViewModel.swift
  iOS/Macro/Macro/Scene/Home/Model/.gitkeep
  iOS/Macro/Macro/Scene/Home/Network/PostEndPoint.swift
  iOS/Macro/Macro/Scene/Home/UseCases/PostSearcher.swift
  iOS/Macro/Macro/Scene/Home/View/HomeViewController.swift
  iOS/Macro/Macro/Scene/Home/ViewModel/.gitkeep
  iOS/MacroDesignSystem/Sources/Network/APIProvider.swift
  iOS/MacroDesignSystem/Sources/Network/Requestable.swift
Labels: feature🔨

#33 [move][#32] 네트워크 모듈 분리 작업
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
  iOS/Macro/Macro/Scene/Home/Network/PostEndPoint.swift
  iOS/Macro/Macro/Scene/Home/UseCases/PostSearcher.swift
  iOS/Macro/Macro/Scene/Travel/Network/TravelEndPoint.swift
  iOS/Macro/Macro/Scene/Travel/UseCases/LocationSearcher.swift
  iOS/Macro/Macro/Scene/Travel/UseCases/PinnedPlaceManager.swift
  iOS/Macro/Macro/Scene/Travel/UseCases/RouteRecorder.swift
  iOS/MacroDesignSystem/Package.swift
  iOS/MacroNetwork/.gitignore
  iOS/MacroNetwork/Package.swift
  iOS/MacroNetwork/Sources/MacroNetwork/APIProvider.swift
  iOS/MacroNetwork/Sources/MacroNetwork/EndPoint.swift
  iOS/MacroNetwork/Sources/MacroNetwork/HTTPHeader.swift
  iOS/MacroNetwork/Sources/MacroNetwork/HTTPHeaders.swift
  iOS/MacroNetwork/Sources/MacroNetwork/HTTPMethod.swift
  iOS/MacroNetwork/Sources/MacroNetwork/HTTPParameter.swift
  iOS/MacroNetwork/Sources/MacroNetwork/MacroNetwork.swift
  iOS/MacroNetwork/Sources/MacroNetwork/NetworkError.swift
  iOS/MacroNetwork/Sources/MacroNetwork/Requestable.swift
  iOS/MacroNetwork/Sources/MacroNetwork/Session.swift
  iOS/MacroNetwork/Tests/MacroNetworkTests/MacroNetworkTests.swift
Labels: feature🔨

#40 [feat][#12] LoginView UI 및 로직 작업
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/App/SceneDelegate.swift
  iOS/Macro/Macro/DTO/LoginDTO/LoginRequest.swift
  iOS/Macro/Macro/DTO/LoginDTO/LoginResponse.swift
  iOS/Macro/Macro/Data/Repository/DefaultLoginRepository.swift
  iOS/Macro/Macro/Data/Repository/MockLoginRepository.swift
  iOS/Macro/Macro/Infrastructure/PersistentStorages/CacheManager.swift
  iOS/Macro/Macro/Infrastructure/PersistentStorages/KeyChainManager.swift
  iOS/Macro/Macro/Macro.entitlements
  iOS/Macro/Macro/Resource/Assets.xcassets/LoginImage.imageset/Contents.json
  iOS/Macro/Macro/Resource/Assets.xcassets/LoginImage.imageset/LoginImage.png
  iOS/Macro/Macro/Resource/Assets.xcassets/LoginImage.imageset/LoginImage@2x.png
  iOS/Macro/Macro/Resource/Assets.xcassets/LoginImage.imageset/LoginImage@3x.png
  iOS/Macro/Macro/Scene/Login/InterfaceAdapters/View/LoginViewController.swift
  iOS/Macro/Macro/Scene/Login/InterfaceAdapters/ViewModel/LoginViewModel.swift
  iOS/Macro/Macro/Scene/Login/Network/Model/HTTPError.swift
  iOS/Macro/Macro/Scene/Login/UseCases/AppleLoginUseCase.swift
Labels: feature🔨

#45 [fix] [#44] validation 오류 수정
  server/src/map/map.kakao.search.accuracy.query.dto.ts
  server/src/map/map.kakao.search.distance.query.dto.ts
Labels: bug fix🐛

#43 [feat][#11] kakao Search에 맞게 DTO 수정
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/App/SceneDelegate.swift
  iOS/Macro/Macro/Common/CommonProtocol/CircularViewProtocol.swift
  iOS/Macro/Macro/Common/CommonProtocol/ViewModelProtocol.swift
  iOS/Macro/Macro/Scene/Travel/Entities/LocationDetail.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/RouteTableViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/RouteTableViewControllerDelegate.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/SearchResultViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
  iOS/Macro/Macro/Scene/Travel/Network/TravelEndPoint.swift
  iOS/Macro/Macro/Scene/Travel/UseCases/PinnedPlaceManager.swift
  iOS/MacroDesignSystem/Sources/MacroDesignSystem/UIImage+.swift
  iOS/MacroNetwork/BaseViewControllerProtocol.swift
Labels: enhancement🩹

#46 [feat][#34] wireframe flow 작업
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/App/SceneDelegate.swift
  iOS/Macro/Macro/Common/CommonProtocol/BaseViewControllerProtocol.swift
  iOS/Macro/Macro/Common/Tab/TabViewController.swift
  iOS/Macro/Macro/Common/TabBar/Model/TabComponent.swift
  iOS/Macro/Macro/Common/TabBar/View/TabBarViewController.swift
  iOS/Macro/Macro/Common/TabBar/View/TabComponentView.swift
  iOS/Macro/Macro/Common/TabBar/ViewModel/TabBarViewModel.swift
  iOS/Macro/Macro/Scene/Search/Entities/.gitkeep
  iOS/Macro/Macro/Scene/Search/InterfaceAdapters/View/SearchViewController.swift
  iOS/Macro/Macro/Scene/Search/InterfaceAdapters/ViewModel/SearchViewModel.swift
  iOS/Macro/Macro/Scene/Search/Network/.gitkeep
  iOS/Macro/Macro/Scene/Search/UseCases/.gitkeep
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift
  iOS/Macro/Macro/Scene/Write/Entities/.gitkeep
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/ViewModel/WriteViewModel.swift
  iOS/Macro/Macro/Scene/Write/Network/.gitkeep
  iOS/Macro/Macro/Scene/Write/UseCases/.gitkeep
Labels: feature🔨

#49 [feat] [#48] User API 초안 작성
  server/src/post/post.module.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.profile.query.dto.ts
  server/src/user/user.service.ts
Labels: feature🔨

#51 [chore][#12] SecneDeleaget Login 화면으로 연결 고정
  iOS/Macro/Macro/App/SceneDelegate.swift
Labels: add

#56 [fix] jwt sign 오류 수정
  server/src/auth/apple/apple.auth.controller.ts
  server/src/auth/apple/apple.auth.service.ts
Labels: bug fix🐛

#59 [add] [#54] 배포 자동화
  .github/workflows/deploy.yaml
  server/.dockerignore
  server/.gitignore
  server/Dockerfile
  server/docker-compose.dev.yaml
  server/docker-compose.prod.yaml
  server/docker-compose.yaml
  server/package.json
  server/production.sh
  server/src/config/app.config.ts
  server/src/entities/post.entity.ts
  server/src/entities/user.entity.ts
  server/src/migrations/1700541570008-Migration.ts
  server/src/mysql.config.ts
Labels: add

#61 [fix] [#60] apple auth 중복 유저 이슈 해결
  server/docker-compose.yaml
  server/package.json
  server/src/auth/apple/apple.auth.service.ts
  server/src/config/app.config.ts
  server/src/entities/post.entity.ts
  server/src/entities/user.entity.ts
  server/src/migrations/1700591341852-Migration.ts
Labels: bug fix🐛

#62 [correct] [#54] Update deploy.yaml
  .github/workflows/deploy.yaml
Labels: bug fix🐛

#64 [feat][#12] Token Manager 구현
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/App/SceneDelegate.swift
  iOS/Macro/Macro/DTO/LoginDTO/LoginRequest.swift
  iOS/Macro/Macro/DTO/LoginDTO/LoginResponse.swift
  iOS/Macro/Macro/Data/Repository/DefaultLoginRepository.swift
  iOS/Macro/Macro/Data/Repository/MockLoginRepository.swift
  iOS/Macro/Macro/Info.plist
  iOS/Macro/Macro/Infrastructure/PersistentStorages/TokenManager.swift
  iOS/Macro/Macro/Scene/Login/Entities/LoginResponse.swift
  iOS/Macro/Macro/Scene/Login/InterfaceAdapters/View/LoginViewController.swift
  iOS/Macro/Macro/Scene/Login/InterfaceAdapters/ViewModel/LoginViewModel.swift
  iOS/Macro/Macro/Scene/Login/Network/Model/LoginEndPoint.swift
  iOS/Macro/Macro/Scene/Login/UseCases/AppleLoginUseCase.swift
Labels: feature🔨

#66 [fix][#50] 유저 이미지 정보가 보이지 않던 버그 수정
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/PostProfileView.swift
Labels: bug fix🐛

#68 [fix][#67] Search가 안되던 버그 수정
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Scene/LocationInfo/InterfaceAdapters/VIew/LocationInfoViewController.swift
  iOS/Macro/Macro/Scene/Travel/Entities/LocationDetail.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
Labels: bug fix🐛

#71 [feat][#70] navigation tab
  iOS/Macro/Macro/Common/TabBar/View/TabBarViewController.swift
Labels: feature🔨

#72 [add] [#65] Object Storage(S3) 셋팅 및 API 초안 작성
  server/package-lock.json
  server/src/app.module.ts
  server/src/auth/apple/apple.auth.controller.ts
  server/src/auth/auth.controller.ts
  server/src/file/file.constants.ts
  server/src/file/file.controller.ts
  server/src/file/file.module.ts
  server/src/file/file.service.ts
  server/src/file/s3.provider.factory.ts
  server/src/main.ts
  server/src/map/map.controller.ts
  server/src/post/post.controller.ts
  server/src/user/user.controller.ts
  server/src/utils/rest.controller.decorator.ts
  server/src/utils/utils.module.ts
Labels: add

#76 [enhancement] [#54] 테이블 수정 및 로직 수정
  server/src/entities/post.entity.ts
  server/src/migrations/1700669514013-Migration.ts
  server/src/post/post.controller.ts
  server/src/post/post.find.query.dto.ts
  server/src/post/post.hist.query.dto.ts
  server/src/post/post.pagenation.dto.ts
  server/src/post/post.read.response.dto.ts
  server/src/post/post.service.ts
  server/src/post/post.write.body.ts
  server/src/user/user.service.ts
  server/src/utils/response.validation.interceptor.ts
Labels: enhancement🩹

#74 [feat][#69] Carousel View 작업
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Common/UI/MacroCarouselView.swift
  iOS/Macro/Macro/Common/UI/MacroCarouselViewCell.swift
Labels: feature🔨

#79 [feat][#67] 경로추천 Segment 의 locationInfo 를 보여주는 기능 구현
  iOS/Macro/Macro/Scene/LocationInfo/InterfaceAdapters/VIew/LocationInfoViewController.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/View/TravelViewController.swift
Labels: feature🔨

#82 [add] [#77] 불필요 로직 제거 및 업로드 로직 개선
  server/src/entities/post.entity.ts
  server/src/entities/user.entity.ts
  server/src/migrations/1700669514013-Migration.ts
  server/src/migrations/1700706919624-Migration.ts
  server/src/migrations/1700709142754-Migration.ts
  server/src/post/post.controller.ts
  server/src/post/post.service.ts
Labels: enhancement🩹, add

#81 [feat][#80] LocationManager 백그라운드 모드 설정
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Info.plist
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
  iOS/Macro/Macro/Util/LocationManager.swift
Labels: feature🔨

#88 [enhancement] PostCollectionView, Common UI 로 활용 가능하도록 수정
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Common/CommonProtocol/PostCollectionViewProtocol.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionView.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostCollectionViewCell.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostContentView.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostProfileView.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/ViewModel/HomeViewModel.swift
  iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoViewController.swift
  iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/ViewModel/UserInfoViewModel.swift
Labels: enhancement🩹

#91 [feat] [#77] Post Api 개선 및 Validation 수정. Swagger 문서 상세화
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/file/file.controller.ts
  server/src/post/post.controller.ts
  server/src/post/post.detail.query.dto.ts
  server/src/post/post.detail.response.dto.ts
  server/src/post/post.pagenation.dto.ts
  server/src/post/post.route.validator.ts
  server/src/post/post.service.ts
  server/src/post/post.write.body.ts
  server/src/user/user.profile.update.query.dto.ts
  server/src/utils/response.validation.interceptor.ts
Labels: enhancement🩹, feature🔨, add

#90 [feat][#89] 기존에 mock 데이터를 불러오던 것을, 서버의 데이터를 불러오도록 구현
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Common/Entities/PostFindResponse.swift
  iOS/Macro/Macro/Common/Entities/Writer.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostContentView.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostProfileView.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/ViewModel/HomeViewModel.swift
  iOS/Macro/Macro/Scene/Home/Network/PostEndPoint.swift
Labels: feature🔨

#93 [feat][#87] mypage의 초기 View 구성
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/ViewModel/MyPageViewModel.swift
Labels: feature🔨

#95 [feat][#84] 이미지 업로드 후 URL 받아오기 구현
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Common/TabBar/ViewModel/TabBarViewModel.swift
  iOS/Macro/Macro/Common/UI/MacroCarouselView.swift
  iOS/Macro/Macro/Common/UI/MacroCarouselViewAddImageCell.swift
  iOS/Macro/Macro/Common/UI/MacroCarouselViewCell.swift
  iOS/Macro/Macro/Info.plist
  iOS/Macro/Macro/Scene/Write/Entities/ImageURLResponse.swift
  iOS/Macro/Macro/Scene/Write/Entities/WriteRequestDTO.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/ViewModel/WriteViewModel.swift
  iOS/Macro/Macro/Scene/Write/Network/ImageUploadEndPoint.swift
  iOS/Macro/Macro/Scene/Write/Network/WriteEndPoint.swift
  iOS/Macro/Macro/Scene/Write/UseCases/UploadImage.swift
Labels: feature🔨

#97 [feat][#94] Launch Screen 구현
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Info.plist
  iOS/Macro/Macro/Resource/Assets.xcassets/LaunchImage.imageset/Contents.json
  iOS/Macro/Macro/Resource/Assets.xcassets/LaunchImage.imageset/LaunchImage.svg
  iOS/Macro/Macro/Scene/LaunchScreen/LaunchScreen.storyboard
Labels: feature🔨

#101 [feat] Route 테이블 추가, Post API 개선 및 기타 작업
  server/package-lock.json
  server/package.json
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/auth/apple/apple.auth.service.ts
  server/src/auth/auth.basic.signin.body.dto.ts
  server/src/auth/auth.basic.signup.body.dto.ts
  server/src/entities/apple.auth.entity.ts
  server/src/entities/post.content.element.entity.ts
  server/src/entities/post.entity.ts
  server/src/entities/route.entity.ts
  server/src/entities/user.entity.ts
  server/src/file/file.upload.response.dto.ts
  server/src/file/s3.provider.factory.ts
  server/src/main.ts
  server/src/migrations/1701051986474-Migration.ts
  server/src/post/post.content.element.base.dto.ts
  server/src/post/post.controller.ts
  server/src/post/post.detail.response.dto.ts
  server/src/post/post.hits.query.dto.ts
  server/src/post/post.like.query.dto.ts
  server/src/post/post.like.response.dto.ts
  server/src/post/post.module.ts
  server/src/post/post.route.validator.ts
  server/src/post/post.service.ts
  server/src/post/post.upload.body.dto.ts
  server/src/post/post.upload.response.dto.ts
  server/src/post/post.write.body.ts
  server/src/route/route.controller.ts
  server/src/route/route.coordinates.dto.ts
  server/src/route/route.coordinates.or.id.dto.ts
  server/src/route/route.module.ts
  server/src/route/route.service.ts
  server/src/route/route.upload.body.dto.ts
  server/src/route/route.upload.response.dto.ts
  server/src/route/route.validator.constrant.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
  server/src/utils/utils.module.ts
Labels: enhancement🩹, feature🔨

#111 [feat] Refresh Token 구현
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/App/SceneDelegate.swift
  iOS/Macro/Macro/Infrastructure/PersistentStorages/KeyChainManager.swift
  iOS/Macro/Macro/Infrastructure/PersistentStorages/TokenManager.swift
  iOS/Macro/Macro/Scene/Login/Entities/RefreshTokenResponse.swift
  iOS/Macro/Macro/Scene/Login/Network/Model/RefreshTokenEndPoint.swift
  iOS/Macro/Macro/Scene/Login/UseCases/RefreshTokenUseCase.swift
Labels: feature🔨

#113 [feat][#96] userInfoView 작업
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Common/TabBar/View/TabBarViewController.swift
  iOS/Macro/Macro/Common/TabBar/ViewModel/TabBarViewModel.swift
  iOS/Macro/Macro/Common/UseCases/SearchUseCase.swift
  iOS/Macro/Macro/Resource/FollowMock.json
  iOS/Macro/Macro/Resource/UserInfoMock.json
  iOS/Macro/Macro/Resource/tempJson.json
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/ViewModel/HomeViewModel.swift
  iOS/Macro/Macro/Scene/UserInfo/Entities/FollowResponse.swift
  iOS/Macro/Macro/Scene/UserInfo/Entities/UserInfoResponse.swift
  iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoHeaderView.swift
  iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoProfileView.swift
  iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoViewController.swift
  iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/ViewModel/UserInfoViewModel.swift
  iOS/Macro/Macro/Scene/UserInfo/Network/FollowEndPoint.swift
  iOS/Macro/Macro/Scene/UserInfo/Network/UserInfoEndPoint.swift
  iOS/Macro/Macro/Scene/UserInfo/UseCases/FollowUseCase.swift
Labels: feature🔨

#121 [feat][#99] ReadView API 연결 작업
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Common/UI/MacroCarouselView.swift
  iOS/Macro/Macro/Common/UI/MacroCarouselViewAddImageCell.swift
  iOS/Macro/Macro/Common/UI/MacroCarouselViewCell.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
  iOS/Macro/Macro/Scene/Read/Entities/ReadPost.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadProfileView.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/ViewModel/ReadViewModel.swift
  iOS/Macro/Macro/Scene/Read/Network/ReadEndPoint.swift
  iOS/Macro/Macro/Scene/Read/UseCases/ReadPostUseCase.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
Labels: feature🔨

#122 [feat][#105] 유저페이지 추가작업
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Info.plist
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/IntroductionEditView.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyInfoViewController.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/NameEditView.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/ViewModel/MyPageViewModel.swift
Labels: feature🔨

#120 [feat][#119] CoreData 작업
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/App/AppDelegate.swift
  iOS/Macro/Macro/CoreData/Macro.xcdatamodeld/Model.xcdatamodel/contents
  iOS/Macro/Macro/Scene/Travel/Entities/TravelInfo.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
  iOS/Macro/Macro/Util/CoreData/CoreDataManager.swift
  iOS/Macro/Macro/Util/CoreData/CoreDataStack.swift
  iOS/Macro/Macro/Util/CoreData/Travels+CoreData.swift
Labels: feature🔨

#127 [feat][#126] postId 타입변경
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Common/CommonProtocol/PostCollectionViewProtocol.swift
  iOS/Macro/Macro/Common/Entities/ProfileGetResponse.swift
  iOS/Macro/Macro/Common/UI/PostCollectionView/PostContentView.swift
  iOS/Macro/Macro/Common/UseCases/SearchUseCase.swift
  iOS/Macro/Macro/Resource/UserInfoMock.json
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/ViewModel/HomeViewModel.swift
  iOS/Macro/Macro/Scene/UserInfo/Entities/UserInfoResponse.swift
  iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoHeaderView.swift
  iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoProfileView.swift
  iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/View/UserInfoViewController.swift
  iOS/Macro/Macro/Scene/UserInfo/InterfaceAdapters/ViewModel/UserInfoViewModel.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
Labels: feature🔨

#136 [feat][#119] CoreData Table Attribute 변경, 로직 변경
  iOS/Macro/Macro/CoreData/Macro.xcdatamodeld/Model.xcdatamodel/contents
  iOS/Macro/Macro/Scene/Travel/Entities/TravelInfo.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
  iOS/Macro/Macro/Util/CoreData/CoreDataManager.swift
Labels: feature🔨

#148 [feat][#143] mypage 수정 작업
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Common/Entities/PatchResponse.swift
  iOS/Macro/Macro/Common/TabBar/ViewModel/TabBarViewModel.swift
  iOS/Macro/Macro/Common/UseCases/PatchUseCase.swift
  iOS/Macro/Macro/Infrastructure/PersistentStorages/TokenManager.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
  iOS/Macro/Macro/Scene/MyPage/Entities/ConfirmError.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyInfoViewController.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/ViewModel/MyPageViewModel.swift
  iOS/Macro/Macro/Scene/MyPage/Network/UpdateUserEndPoint.swift
  iOS/Macro/Macro/Scene/MyPage/UseCases/ComfirmUseCase.swift
  iOS/Macro/Macro/Scene/Search/InterfaceAdapters/View/SearchViewController.swift
Labels: feature🔨

#150 [fix] [#149] post detail 오류 수정 및 dto 수정
  server/src/entities/post.content.element.entity.ts
  server/src/entities/route.entity.ts
  server/src/post/post.content.element.base.dto.ts
  server/src/post/post.detail.response.dto.ts
  server/src/post/post.service.ts
  server/src/post/post.upload.body.dto.ts
  server/src/route/route.coordinates.dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.profile.update.response.dto.ts
  server/src/user/user.service.ts
  server/src/utils/nicknamedata.json
Labels: bug fix🐛

#152 [feat][#151] RouteView 작업
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Common/CommonProtocol/MapCollectionViewProtocol.swift
  iOS/Macro/Macro/Common/TabBar/ViewModel/TabBarViewModel.swift
  iOS/Macro/Macro/Common/UI/MapCollectionView/MapCollectionView.swift
  iOS/Macro/Macro/Common/UI/MapCollectionView/MapCollectionViewCell.swift
  iOS/Macro/Macro/Common/UI/MapCollectionView/MapCollectionViewCellContentView.swift
  iOS/Macro/Macro/Common/UI/MapCollectionView/MapCollectionViewCellHeaderView.swift
  iOS/Macro/Macro/Scene/Home/InterfaceAdapters/View/HomeViewController.swift
  iOS/Macro/Macro/Scene/Route/InterfaceAdapters/View/RouteViewController.swift
  iOS/Macro/Macro/Scene/Route/InterfaceAdapters/ViewModel/RouteViewModel.swift
  iOS/Macro/Macro/Scene/Travel/Entities/TravelInfo.swift
  iOS/Macro/Macro/Scene/Travel/InterfaceAdapters/ViewModel/TravelViewModel.swift
  iOS/Macro/Macro/Util/CoreData/CoreDataManager.swift
  iOS/Macro/Macro/Util/CoreData/CoreDataStack.swift
  iOS/Macro/Macro/Util/CoreData/Travels+CoreData.swift
  iOS/Macro/Macro/Util/DateFormatter.swift
  iOS/MacroDesignSystem/Sources/MacroDesignSystem/UIImage+.swift
Labels: feature🔨

#153 [feat] WriteView API 연결
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Common/Entities/Coordinate.swift
  iOS/Macro/Macro/Common/Entities/Cotent.swift
  iOS/Macro/Macro/Common/Entities/Post.swift
  iOS/Macro/Macro/Common/UI/MacroCarouselView.swift
  iOS/Macro/Macro/Infrastructure/PersistentStorages/ImageSaveManager.swift
  iOS/Macro/Macro/Scene/Read/Entities/ReadPost.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadProfileView.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/View/ReadViewController.swift
  iOS/Macro/Macro/Scene/Read/InterfaceAdapters/ViewModel/ReadViewModel.swift
  iOS/Macro/Macro/Scene/Route/InterfaceAdapters/ViewModel/RouteViewModel.swift
  iOS/Macro/Macro/Scene/Write/Entities/PostUploadResponse.swift
  iOS/Macro/Macro/Scene/Write/Entities/WriteRequestDTO.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/View/WriteViewController.swift
  iOS/Macro/Macro/Scene/Write/InterfaceAdapters/ViewModel/WriteViewModel.swift
  iOS/Macro/Macro/Scene/Write/Network/PostUploadEndPoint.swift
  iOS/Macro/Macro/Scene/Write/Network/WriteEndPoint.swift
  iOS/Macro/Macro/Scene/Write/UseCases/UploadPost.swift
  iOS/MacroNetwork/Sources/MacroNetwork/APIProvider.swift
Labels: feature🔨

#155 [feat][#154] MyPage 디자인 디테일 작업
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageHeaderView.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/View/MyPageViewController.swift
  iOS/Macro/Macro/Scene/MyPage/InterfaceAdapters/ViewModel/MyPageViewModel.swift
Labels: enhancement🩹

#162 [feat][#156] iOS, BE 의 Task 를 공유하기 위한 ipa, testflight 작업
  iOS/Macro/Macro.xcodeproj/project.pbxproj
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/100.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/102.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/128.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/144.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/152.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/16.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/167.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/172.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/196.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/20.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/216.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/256.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/32.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/48.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/50.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/512.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/55.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/64.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/66.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/72.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/76.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/88.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/92.png
  iOS/Macro/Macro/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: feature🔨
